services:
  - type: web
    name: dailyspark
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: false
        scope: build
      - key: NODE_ENV
        value: production
        scope: run
      - key: FIREBASE_API_KEY
        scope: run
      - key: FIREBASE_AUTH_DOMAIN
        scope: run
      - key: FIREBASE_PROJECT_ID
        scope: run
      - key: FIREBASE_STORAGE_BUCKET
        scope: run
      - key: FIREBASE_MESSAGING_SENDER_ID
        scope: run
      - key: FIREBASE_APP_ID
        scope: run
      - key: STRIPE_PUBLISHABLE_KEY
        scope: run
      - key: STRIPE_SECRET_KEY
        scope: run
