services:
  - type: web
    name: dailyspark
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_API_KEY
        scope: run
      - key: FIREBASE_AUTH_DOMAIN
        scope: run
      - key: FIREBASE_PROJECT_ID
        scope: run
      - key: FIREBASE_STORAGE_BUCKET
        scope: run
      - key: FIREBASE_MESSAGING_SENDER_ID
        scope: run
      - key: FIREBASE_APP_ID
        scope: run
      - key: STRIPE_PUBLISHABLE_KEY
        scope: run
      - key: STRIPE_SECRET_KEY
        scope: run
